# Generated by Django 3.2.7 on 2021-09-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
